// Leçon « Le gambit du Centre » — d'après le PGN commenté (09/08/2025) : introduction,
// 8.Dg3 Cxe4 !, 8.Dg3 Txe4 et 8.Fc4 de Nepomniachtchi. Format décrit dans ../jobava/lecon.mjs.

export const meta = {
  title: 'Le gambit du Centre',
  kicker: 'Leçon d\'ouverture · Objectif 1600-1800',
  author: '1.e4 e5 2.d4 exd4 3.Dxd4',
  orientation: 'white',
};

const MAIN = 'Partie principale';

export const beats = [
  { card: { k: 'Leçon d\'ouverture · Objectif 1600-1800', t: 'Le gambit du Centre', s: '1.e4 e5 2.d4 exd4 3.Dxd4', pose: 'idee' },
    say: 'Bonjour à tous ! Aujourd\'hui, on étudie une ouverture qui fait peur : le gambit du Centre. Une arme d\'attaque pour les Blancs, avec des grands roques, des sacrifices, et des pièges partout. On va voir les idées blanches, les défenses noires les plus précises, et surtout pourquoi, en pratique, rien n\'est simple.' },

  // ── Chapitre 1 ─────────────────────────────────────────────
  { card: { k: 'Chapitre 1', t: 'L\'idée du gambit', pose: 'regarde' } },
  { ch: 'L\'idée du gambit', line: MAIN, from: 'start', play: 'e4 e5 d4 exd4',
    say: 'Tout commence par ^e4, ^e5, puis ^d4 ! Les Noirs prennent : ^e prend d4.' },
  { play: 'Qxd4', mark: 'Qxd4', sq: 'Ye4', arrows: 'Gd4d8',
    say: 'Et les Blancs reprennent tout de suite avec la Dame : Dame prend d4. Voilà le gambit du Centre ! Autant vous le dire tout de suite : c\'est stratégiquement très risqué.' },
  { key: 'Le « petit centre » : un pion de plus au centre… mais une Dame exposée.', sq: 'Ye4 Gd4',
    say: 'Certes, les Blancs obtiennent ce qu\'on appelle le petit centre : # un pion de plus au centre que leur adversaire. Mais le prix à payer est assez élevé. La Dame blanche, sortie très tôt, va rapidement se faire chasser.' },
  { play: 'Nc6', arrows: 'Rc6d4', ev: '',
    say: 'Et justement : Cavalier c6, avec gain de temps sur la Dame. Attention quand même, les Noirs doivent jouer avec précision. Des roques opposés peuvent survenir, et cette Dame peut soudain devenir très dangereuse si les Blancs lancent une attaque sur le Roi.' },

  // ── Chapitre 2 ─────────────────────────────────────────────
  { card: { k: 'Chapitre 2', t: '4.De3 : place au grand roque', pose: 'reflexion' } },
  { ch: '4.De3', play: 'Qe3', mark: 'Qe3', arrows: 'Ge1c1 Ga1d1', key: 'De3 libère la première rangée pour le grand roque.',
    say: 'Dame e3 : c\'est le coup principal, même si ces dernières années, Dame c4 ou Dame d3 ont aussi été tentés. Retenez bien l\'idée : # en sortant la Dame dès le début, les Blancs veulent libérer la première rangée côté aile Dame, pour faire le grand roque au plus vite.' },
  { line: 'Variante : 4...d6?!', play: 'd6?! Nc3 Nf6 Bd2! Be7 O-O-O O-O', ev: '',
    say: 'Si les Noirs jouent tranquillement ^d6, c\'est beaucoup trop passif. Regardez la facilité blanche : ^Cavalier c3, ^Cavalier f6, ^Fou d2 !, ^Fou e7, ^grand roque, ^petit roque…' },
  { play: 'Qg3 Nh5 Qf3 Nf6 h3 Rb8 g4', ev: '+−', arrows: 'Gg4g5 Gh3h4 Gd1g1', key: 'Roques opposés : les pions blancs foncent sur le Roi noir.',
    say: '^Dame g3, ^Cavalier h5, ^Dame f3, ^Cavalier f6, ^h3, ^Tour b8, et ^g4 ! # Les pions blancs vont foncer sur le Roi noir : avec les roques opposés, c\'est une très belle attaque qui se prépare.' },
  { from: 'Qe3', line: 'Variante : 4...g6', play: 'g6 Nc3 Bg7',
    say: 'Autre idée pour les Noirs : ^g6, ^Cavalier c3, puis ^Fou g7. Mais là encore, les Blancs ont un jeu très agréable.' },
  { play: 'h4! Nf6 h5! Nxh5', ev: '+−', arrows: 'Gh1h5',
    say: 'Par exemple ^h4 !, ^Cavalier f6, ^h5 !, et si les Noirs prennent, ^Cavalier prend h5, # la colonne h s\'ouvre. Les Blancs ont un net avantage, même avec des pions de moins : leur avance de développement leur permet de lancer une attaque très forte.' },
  { from: 'Qe3', line: MAIN, quiz: 'Quel est le meilleur coup de développement pour les Noirs ?', pause: 5,
    say: 'Alors, quel est le bon coup pour les Noirs ? À vous de jouer !' },
  { play: 'Nf6!', key: '...Cf6 ! : développement actif, pression sur e4.', arrows: 'Rf6e4', mark: 'Nf6',
    say: 'Cavalier f6 ! Le coup le plus naturel : # on développe et on attaque tout de suite le pion e4.' },

  // ── Chapitre 3 ─────────────────────────────────────────────
  { card: { k: 'Chapitre 3', t: 'La position critique', pose: 'regarde' } },
  { ch: 'La position critique', play: 'Nc3 Bb4!', mark: 'Bb4', arrows: 'Rb4c3 Rf6e4', key: '...Fb4 ! : le seul vrai défi, e4 est menacé.',
    say: 'Les Blancs défendent avec ^Cavalier c3, et ^Fou b4 ! C\'est le seul vrai défi : # le Cavalier c3 est cloué, et le pion e4 devient une cible.' },
  { from: 'Nf6', line: 'Variante : 5...Fe7?!', play: 'Nc3 Be7?! Bc4 O-O Nf3', ev: '⩲',
    say: 'Petite parenthèse : après ^Cavalier c3, ^Fou e7 marche moins bien, car les Blancs choisissent un développement plus actif avec ^Fou c4, ^petit roque, ^Cavalier f3. Ils gardent un petit avantage, et une position facile à jouer.' },
  { from: 'Bb4', line: MAIN, play: 'Bd2 O-O O-O-O', mark: 'OOO', arrows: 'Gd1d7', key: 'Grand roque : la Tour d1 vise déjà la colonne d.',
    say: '^Fou d2 défend le Cavalier. Les Noirs mettent leur Roi à l\'abri, ^petit roque, et les Blancs font ce qu\'ils voulaient : ^grand roque !' },
  { play: 'Re8!', arrows: 'Re8e4 Gd7d5', mark: 'Re8', key: '...Te8 ! : pression sur e4, les Noirs veulent jouer ...d5.',
    say: 'Tour e8 ! La seule bonne réaction noire. # Le pion e4 est attaqué deux fois, et les Noirs préparent la poussée d7-d5. Nous voici dans la position critique. Et les Blancs ont deux coups : Dame g3, et Fou c4.' },

  // ── Chapitre 4 ─────────────────────────────────────────────
  { card: { k: 'Chapitre 4', t: '8.Dg3 Cxe4 ! : ma recommandation', pose: 'idee' } },
  { ch: '8.Dg3 Cxe4 !', line: MAIN, play: 'Qg3!?', arrows: 'Gg3g7', sq: 'Re4', key: 'Dg3 !? : on sacrifie e4 pour gagner du temps.',
    say: 'Dame g3 ! Un coup choquant de prime abord : # le pion e4 est abandonné ! Mais c\'est toute l\'idée de la ligne : sacrifier ce pion pour gagner du temps pour l\'attaque. Les ordinateurs clament que les Noirs sont bien, mais sur l\'échiquier, avec toutes les pièces noires de l\'aile Dame engluées, le ressenti est très différent !', mark: 'Qg3' },
  { play: 'Nxe4! Nxe4 Rxe4', sq: 'Ge4',
    say: 'Pour les Noirs, ma recommandation : ^Cavalier prend e4 ! Il n\'y a pas si longtemps, on considérait ça comme un très mauvais coup, mais les ordinateurs ont changé la donne. ^Cavalier prend e4, ^Tour prend e4.' },
  { play: 'c3', arrows: 'Rc3b4', mark: 'c3',
    say: 'c3 ! Le Fou b4 est attaqué, et c\'est là que les Noirs doivent trouver une manœuvre difficile.' },
  { quiz: 'Où replier le Fou b4 ?', pause: 5,
    say: 'Où les Noirs doivent-ils replier leur Fou ? À vous de trouver !' },
  { play: 'Be7!!', arrows: 'Ge7h4', key: '...Fe7 !! : le Fou vise h4, et donc la Dame g3.',
    say: 'Fou e7 ! Un coup tout sauf naturel, alors que la Tour e4 fait pâle figure au milieu de l\'échiquier. Mais l\'idée est cachée : # Fou h4, qui chasserait la Dame g3.' },
  { line: 'Variante : 11.Fd3??', play: 'Bd3?? Bh4!!', arrows: 'Rh4g3 Re4d4', ev: '−+',
    say: 'Par exemple, si les Blancs jouent naturellement ^Fou d3 : ^Fou h4 ! Seul ce coup sauve les Noirs… # mais s\'ils le trouvent, tout redevient simple pour eux.' },
  { from: 'c3', line: MAIN, play: 'Be7 Nf3!', arrows: 'Gf3h4', key: 'Cf3 ! empêche ...Fh4.',
    say: 'Après ^Fou e7, les Blancs doivent donc jouer ^Cavalier f3 !, qui contrôle la case h4.' },
  { play: 'Ra4!!', arrows: 'Ga4a2', mark: 'Ra4', key: '...Ta4 !! : gagnant selon l\'ordinateur, suicidaire pour un humain.',
    say: 'Et voici le coup de l\'ordinateur : Tour a4 ! C\'est gagnant d\'après la machine, même si ça a l\'air complètement suicidaire pour un humain. # La Tour vise le pion a2, et le Roi blanc.' },
  { from: 'Ra4', play: 'Bd3 d5! Bf4 Bd6! Bxd6 cxd6', arrows: 'Gd8a5 Ga4a2', key: 'Plus de Txd5 possible : le Fou d3 bloque la colonne d.',
    say: '^Fou d3, ^d5 !, ^Fou f4, ^Fou d6 !, ^Fou prend d6, ^c prend d6. # Et voici la différence avec d5 joué trop tôt : le Fou d3 bloque la colonne d, donc les Blancs n\'ont plus Tour prend d5.' },
  { play: 'h3 Rxa2! Kb1 Qa5', ev: '−+', arrows: 'Ra5a1 Ra2b2', sq: 'Rb1',
    say: '^h3, ^Tour prend a2 !, ^Roi b1, ^Dame a5, # et l\'attaque noire est dévastatrice. Le chasseur est devenu la proie !' },

  // ── Chapitre 5 ─────────────────────────────────────────────
  { card: { k: 'Chapitre 5', t: '8.Dg3 Txe4 : l\'ancien antidote', pose: 'reflexion' } },
  { ch: '8.Dg3 Txe4', line: 'Variante : 8...Txe4', from: 'Qg3', play: 'Rxe4!', sq: 'Ge4',
    say: 'Pendant très longtemps, Tour prend e4 était considéré comme l\'antidote au gambit du Centre. Mais en pratique, rien n\'est simple pour les Noirs.' },
  { play: 'a3!', arrows: 'Ra3b4', mark: 'a3', key: 'a3 ! chasse le Fou avant tout.',
    say: 'a3 ! Le Fou b4 est attaqué, et les Noirs doivent déjà faire un choix délicat.' },
  { line: 'Variante : 9...Tg4', play: 'Rg4 Qe3! Ba5 f3! Rd4 Nge2! Nd5 Nxd5 Rxd5 Nc3 Re5 Qf4!',
    say: 'Le coup naturel, ^Tour g4, ne résout rien. ^Dame e3 !, ^Fou a5, ^f3 !, ^Tour d4, ^Cavalier e2 !, ^Cavalier d5, ^Cavalier prend d5, ^Tour prend d5, ^Cavalier c3, ^Tour e5, ^Dame f4 !' },
  { play: 'd6 h4 Be6 Bd3 Qd7 g4', arrows: 'Gg4g5 Gh4h5', key: 'Un pion de moins, mais une attaque très dangereuse en pratique.', ev: '',
    say: 'Les Noirs ont un pion de plus, mais leur développement laisse à désirer. Après ^d6, ^h4, ^Fou e6, ^Fou d3, ^Dame d7, ^g4, # les Blancs ont une très belle attaque. Quoi qu\'en dise l\'ordinateur, ces positions sont très dangereuses en pratique.' },
  { from: 'a3', line: 'Variante : 8...Txe4', play: 'Bd6!', sq: 'Rd7', key: '...Fd6 ! : le meilleur, même s\'il bloque le pion d7.',
    say: 'Le meilleur coup, c\'est Fou d6 ! Mais avouez que sans connaître, on n\'a pas envie de le jouer : # le Fou bloque le pion d7.' },
  { play: 'f4 Re8 Bd3 Bf8 Nf3 d5!', arrows: 'Gd5d4',
    say: '^f4, ^Tour e8, ^Fou d3, ^Fou f8, ^Cavalier f3, ^d5 ! C\'était l\'ancienne grande variante, qui marche toujours. Mais là encore, les choses ne sont pas si simples.' },
  { play: 'Rhe1 Rxe1 Rxe1 Ne7!!', arrows: 'Ge7f5 Ge7g6', key: '...Ce7 !! : très difficile à voir de loin.',
    say: '^Tour h e1, ^Tour prend e1, ^Tour prend e1, et ^Cavalier e7 ! Le plus fort, mais il est très difficile de voir un tel coup de loin, par exemple au moment où l\'on calcule Fou d6.' },
  { play: 'Ne5 c5 Qf2 c4 Be2 Be6 Rd1 Nc6', ev: '∓',
    say: '^Cavalier e5, ^c5, ^Dame f2, ^c4, ^Fou e2, ^Fou e6, ^Tour d1, ^Cavalier c6. Les Noirs ont gardé le pion de plus, avec un net avantage… mais tout reste à faire !' },

  // ── Chapitre 6 ─────────────────────────────────────────────
  { card: { k: 'Chapitre 6', t: '8.Fc4 : l\'arme de Nepomniachtchi', pose: 'lecture' } },
  { ch: '8.Fc4 de Nepo', line: 'Variante : 8.Fc4', from: 'Re8', play: 'Bc4!?', arrows: 'Gc4f7',
    say: 'Revenons à la position critique. Fou c4 ! Le coup de l\'ex-challenger Ian Népomniachtchi, une alternative très intéressante à Dame g3.' },
  { play: 'd6 Nf3 Be6 Bxe6 Rxe6 Ng5 Re8', arrows: 'Gg5f7 Gg5h7',
    say: '^d6, ^Cavalier f3, ^Fou e6, ^Fou prend e6, ^Tour prend e6, ^Cavalier g5, # qui vise f7 et h7, et ^Tour e8.' },
  { play: 'a3!?', mark: 'a3nepo', arrows: 'Ra3b4', key: 'a3 !? : la nouvelle idée de Nepo, venimeuse en partie rapide.',
    say: 'a3 ! C\'est la nouvelle idée de Népo. L\'ordinateur préfère les Noirs, mais ça peut avoir beaucoup de venin en pratique, surtout en parties rapides.' },
  { line: 'Variante : 12...Fxc3 (Caruana)', play: 'Bxc3 Bxc3 h6 h4! hxg5? hxg5 Nxe4 Qh3 Kf8', sq: 'Rg7',
    say: 'Caruana a joué ^Fou prend c3 en blitz. Après ^Fou prend c3, ^h6, ^h4 !, c\'est très dangereux. Par exemple, si les Noirs prennent : ^h prend g5 ?, ^h prend g5, ^Cavalier prend e4, ^Dame h3, ^Roi f8, et les Noirs croient s\'en sortir…' },
  { quiz: 'Les Blancs ont un coup fulgurant. Lequel ?', pause: 6,
    say: 'Mais les Blancs ont un coup fulgurant. À vous de le trouver !' },
  { play: 'Bxg7+!!', ev: '+−', arrows: 'Rg7h8 Gh3h8', key: 'Fxg7+ !! : la colonne h décide. Nepomniachtchi – Santos Latasa, 2025.',
    say: 'Fou prend g7 échec ! Après Roi e7, Tour h e1, et c\'est gagnant pour les Blancs. # C\'était la partie Népomniachtchi contre Santos Latasa, en 2025.' },
  { from: 'a3nepo', line: 'Variante : 8.Fc4', play: 'Ba5!', key: '...Fa5 ! : le meilleur, rien d\'évident.',
    say: 'Le meilleur coup pour les Noirs, c\'est Fou a5 ! Mais croyez-moi, il n\'y a rien d\'évident là-dedans.' },
  { play: 'Qg3 h6!!', arrows: 'Rh6g5', key: '...h6 !! : si h4, alors ...hxg5 est possible.',
    say: 'Après ^Dame g3, les Noirs évitent souvent ^h6, par peur de h4. Pourtant, c\'est le seul coup qui pose vraiment problème à la ligne de Népo ! # La vraie idée blanche était Tour h e1 et e5. Après h6 et h4, les Noirs peuvent prendre le Cavalier sans problème.' },
  { play: 'h4 b5! Nxb5 Bxd2+ Rxd2 Rb8 Nc3 Ne5 f4', key: 'Les Blancs sont « condamnés » à l\'attaque directe.',
    say: '^h4, et les Blancs sont condamnés à l\'attaque directe. ^b5 !, ^Cavalier prend b5, ^Fou prend d2 échec, ^Tour prend d2, ^Tour b8, ^Cavalier c3, ^Cavalier e5, ^f4…' },
  { quiz: 'Où va le Cavalier e5 ?', pause: 5,
    say: 'Et maintenant, un coup incroyable pour les Noirs. Où va le Cavalier e5 ?' },
  { play: 'Nh5!!', arrows: 'Rh5g3', key: '...Ch5 !! : qui peut trouver ça en partie ? Personne !',
    say: 'Cavalier h5 ! Qui va trouver ça dans une telle position ? Personne !' },
  { game: 'Ligne forcée · nulle par échecs perpétuels', fast: 0.5,
    play: 'Qf2 Nc4 Rd4 Nxb2 Qf3! Qf6 e5 dxe5 fxe5 Rxe5 Rb4 Ree8 Kxb2 hxg5 Qxh5 Qd4! Qf3 Rxb4+ axb4 Qxb4+ Kc1 Qa3+ Kd2 Rd8+ Ke2 Re8+ Kd2 Rd8+',
    say: 'La suite est d\'une précision folle : tout ne tient qu\'à un fil, mais la position reste égale, et la partie se termine par des échecs perpétuels. Bonne chance pour trouver toute cette ligne sur l\'échiquier !' },

  // ── Bilan ─────────────────────────────────────────────────
  { card: { k: 'À retenir', t: 'Le gambit du Centre', pose: 'lecon-terminee', bullets: [
      '3.Dxd4 : petit centre, mais la Dame se fait chasser',
      '4.De3 puis grand roque : roques opposés et attaque',
      'Position critique : ...Cf6, ...Fb4, ...0-0, ...Te8 !',
      '8.Dg3 Cxe4 ! et 10...Fe7 !!, 11...Ta4 !! pour les Noirs',
    ] },
    say: 'Récapitulons. Un : Dame prend d4 donne le petit centre, mais la Dame blanche se fait chasser. Deux : Dame e3 puis le grand roque, avec des roques opposés et une attaque rapide. Trois : la défense noire la plus précise, Cavalier f6, Fou b4, le roque, et Tour e8 ! Et quatre : contre Dame g3, Cavalier prend e4, puis Fou e7 et Tour a4 ! Avec les Blancs, c\'est une arme redoutable en partie rapide. Avec les Noirs, il faut connaître ces coups par cœur !' },
];
